name: Demo Workflow

on:
  workflow_dispatch:
    inputs:
      greeting:
        description: "Who to Greet"
        required: true
        default: octocat
        
jobs:
  demo:
    name: Demo Workflow
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello Sabre Team 👋"
